# Generated by Django 5.0.3 on 2024-03-10 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='images',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
