# Generated by Django 5.0.9 on 2024-11-07 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_reciever_feedback_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='chairperson',
        ),
        migrations.AddField(
            model_name='department',
            name='chairpersons',
            field=models.ManyToManyField(blank=True, related_name='chaired_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
