# Generated by Django 5.0.2 on 2024-02-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Student', 'Student'), ('Chairperson', 'Chairperson')], default='Student', max_length=25),
        ),
    ]
